networks:
  default: mainnet-fork
  mainnet-fork:
    cmd_settings:
      unlock:
        - 0x5d3a536E4D6DbD6114cc1Ead35777bAB948E3643
        - 0x39aa39c021dfbae8fac545936693ac917d5e7563
        - 0xc11b1268c1a384e55c48c2391d8d480264a3a7f4
        - 0x93054188d876f558f4a66B2EF1d97d16eDf0895B

autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.0.0

compiler:
  solc:
    version: 0.8.0
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.0.0"

reports:
  exclude_contracts:
    - SafeMath
