# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing

networks:
  default: mainnet-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.0.0-beta.1

compiler:
  solc:
    version: 0.8.0
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.0.0-rc.0"
reports:
  exclude_contracts:
    - SafeMath
