networks:
  default: geth-node
  name: Ganache-CLI (Geth Mainnet Fork)
  id: geth-node
  host: http://127.0.0.1
  cmd: ganache-cli
  cmd_settings:
    fork: http://192.168.1.191:9545
    gas_limit: 10000000
    port: 8545
    accounts: 10
    mnemonic: brownie
    unlock:
      - 0x5d3a536E4D6DbD6114cc1Ead35777bAB948E3643
      - 0x39aa39c021dfbae8fac545936693ac917d5e7563
      - 0xc11b1268c1a384e55c48c2391d8d480264a3a7f4
      - 0x93054188d876f558f4a66B2EF1d97d16eDf0895B
      - 0x47ac0Fb4F2D84898e4D9E7b4DaB3C24507a6D503
      - 0x13aec50f5D3c011cd3fed44e2a30C515Bd8a5a06
      - 0x16463c0fdB6BA9618909F5b120ea1581618C1b9E
      - 0xB60eF661cEdC835836896191EDB87CC025EFd0B7


autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.1.0
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.1.0

compiler:
  solc:
    version: null
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.1.0"
      - "@openzeppelinupgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.1.0"

hypothesis:
  deadline: null
  max_examples: 25
  report_multiple_bugs: False
  stateful_step_count: 10
  phases:
    explicit: true
    reuse: true
    generate: true
    target: true
    shrink: true

reports:
  exclude_contracts:
    - SafeMath
